### ISSUE TITLE
rotation event details are position's

### ISSUE THREAD

**Issue by riebling** [urish/aframe-camera-events#1]
Sorry false alarm. Was seeing only an x,y,z as rotation, and was like "where's the fourth quaternion w value?" but unfortunately A-Frame puts rotations into Eulers, then, worse, into degrees. I know, it's more human readable, but harder to interface with systems that use Quaternions (Unity, OptiTrack...)

**Comment by riebling** [comment]
Wow it really looks like I pluralized "position" with an apostrophe, when actually I mean that the details belong to a position. :)

**Comment by urish** [comment]
👍
